Add "Next rank" to rank command
Bobby-McBobface/phnix-discord-bot pull request #21
Opened 2021-06-23 10:59 UTC by Awakened-Redstone

2021-06-23 12:54 UTC, Bobby-McBobface requested changes
+7 lines, +3 errors. Do you mind testing before submitting a pull reuqest?

2021-06-23 12:54 UTC, Bobby-McBobface commented on src/commands/level.py
> +        rank = ranks[ranks.lenght() - 1].value()
```suggestion
        rank = ranks[len(ranks) - 1].value()
```

2021-06-23 12:54 UTC, Bobby-McBobface commented on src/commands/level.py
> +    if ranks.lenght() > 0:
```suggestion
    if len(ranks) > 0:
```

2021-06-23 12:54 UTC, Bobby-McBobface commented on src/commands/level.py
> +    ranks = configuration.LEVEL_ROLES.filter(lambda key, value: level - 1 < value[1])
Filter not a attribute of dict

2021-06-23 13:15 UTC, Awakened-Redstone commented on src/commands/level.py
> +    ranks = configuration.LEVEL_ROLES.filter(lambda key, value: level - 1 < value[1])
```suggestion
    ranks = dict(filter(lambda elem: level < elem[1][1], configuration.LEVEL_ROLES.items()))
```

2021-06-23 13:21 UTC, Bobby-McBobface requested changes

2021-06-23 13:21 UTC, Bobby-McBobface commented on src/commands/level.py
> +    ranks = dict(filter(lambda elem: level < elem[1][1], configuration.LEVEL_ROLES.items()))
```suggestion
    ranks = dict(filter(lambda elem: level - 1< elem[1][1], configuration.LEVEL_ROLES.items()))
```
Compensate for #9

2021-06-23 13:25 UTC, Awakened-Redstone commented on src/commands/level.py
> +        rank = ranks[len(ranks) - 1].value()
```suggestion
        rank = list(ranks.items())[len(ranks) - 1][1]
```

2021-06-23 13:59 UTC, Awakened-Redstone commented on src/commands/level.py
> +    ranks = dict(filter(lambda elem: level - 1< elem[1][1], configuration.LEVEL_ROLES.items()))
```suggestion
    ranks = dict(filter(lambda elem: user_xp[1] - 1 < elem[1][1], configuration.LEVEL_ROLES.items()))
```

2021-06-25 08:10 UTC, Bobby-McBobface approved these changes

2021-06-25 08:11 UTC, merged