Rework the bot
Bobby-McBobface/phnix-discord-bot pull request #6
Opened 2021-05-03 13:05 UTC by Bobby-McBobface

2021-05-03 13:26 UTC, Awakened-Redstone commented
Please note it uses .env

1st run .env example:
```
TOKEN=bot_token
TWITCH_CLIENT_ID=twitch_client_id
TWITCH_SECRET=twitch_secret
TWITCH_AUTH_TOKEN=
```
The twitch auth token will be filled automatically

2021-05-03 18:25 UTC, Awakened-Redstone commented
Please test the modular levels before merging this into master

2021-05-03 18:29 UTC, Awakened-Redstone requested changes
Test if modular levels works, it was not tested and may not work properly.

2021-05-03 18:29 UTC, Awakened-Redstone commented on src/main/levels.py
> +
Has to be tested

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +                return False
```suggestion
            if user.id not in await reaction.users().flatten():
                return False
```

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +            emoji = reaction.emoji
```suggestion
            emoji = reaction.emoji
            
            valid = emoji == "◀️" or emoji == "▶️"
            if not valid:
                return False

        
```

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/other/help.py
> +                        arguments += f" [{argument.identifier}]"
```suggestion
                arguments = ''.join(f" <{argument.identifier}>" if argument.required else f" [{argument.identifier}]"
```

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/other/help.py
> +                return command_().command == parameters or parameters in command_().alias
Defining a new one each run

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/other/help.py
> +        if not parameters or parameters == '':
```suggestion
        if not parameters:
```
Empty string is false in python

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +            return valid
```suggestion
            if emoji == "◀️" and page > 0:
                page += -1
            elif emoji == "▶️":
                page += 1
            return True
```

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +            await self.change_page(message, page - 1, client)
```suggestion
        await self.change_page(message, page, client)
```

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +        embed = discord.Embed(title="Leaderboard", description=lb_list)
Keep it dry

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/command/leveling/leaderboards.py
> +        embed = discord.Embed(title="Leaderboard", description=lb_list)
Keep it dry

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/listener/messageReactionListener.py
> +        await reaction.remove(user)
Do not need this file

2021-05-04 08:28 UTC, Bobby-McBobface commented on src/main/main.py
> +        await messageReactionListener.on_reaction_add(reaction, user)
```suggestion
```

2021-05-04 08:38 UTC, Neron-png commented on config.json
> +}
It uses camel case, it's fine as long as it is consistent

2021-05-04 08:45 UTC, Neron-png commented on src/main/command/leveling/leaderboards.py
> +            print('aaaaaaaaaaa')
```suggestion
```
Better remove line 34 from the master version, as it's in for debug purposes and will spam the terminal.

2021-05-04 08:50 UTC, Neron-png commented on src/main/listener/messageReactionListener.py
> +        await reaction.remove(user)
Is this just for debugging?

2021-05-04 08:53 UTC, Neron-png approved these changes
I suggest we run it on the test server before we roll this out

2021-05-04 08:59 UTC, merged

2021-05-04 12:13 UTC, Awakened-Redstone commented on src/main/listener/messageReactionListener.py
> +        await reaction.remove(user)
was testing reaction listener